apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-app-pvc
  namespace: python
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
