apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: python
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - port: 5000
      targetPort: 5001
      nodePort: 30500
